# Maintained by devKloud بالعربي
# @devkloud-arabic

name: excalidraw

networks:
  proxy: {}

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      - HTTPS_METHOD=redirect
    labels:
      - com.github.nginx-proxy.nginx=true
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/certs:/etc/nginx/certs:ro
      - ./data/vhost:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
    networks: [proxy]

  acme-companion:
    image: nginxproxy/acme-companion:latest
    container_name: nginx-proxy-acme
    restart: unless-stopped
    environment:
      - DEFAULT_EMAIL=info@example.com
      - NGINX_PROXY_CONTAINER=nginx-proxy
    depends_on:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/certs:/etc/nginx/certs:rw
      - ./data/vhost:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/acme:/etc/acme.sh
    networks: [proxy]

  draw:
    image: excalidraw/excalidraw:latest
    container_name: draw
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=draw.example.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=draw.example.com
      - LETSENCRYPT_EMAIL=info@example.com
    networks: [proxy]
